# Unity test build
# Usage: make -f tests/Makefile.unity [test|clean]

BUILD_DIR ?= build
CC      := gcc
CFLAGS   = -MMD -MP -std=c99 -fPIC -pedantic -Wall -Wextra -Werror -I. -Isrc -Itests/unit -Itests/unit/mocks -I$(BUILD_DIR) -DSYN_LOG_COLOR=1 -DSYN_USE_COREDUMP=1 -DSYN_COREDUMP_FLASH_ADDR=0 -DSYN_USE_TICKLESS=1 -DSYN_USE_DMA=1 -DSYN_USE_I2C_ASYNC=1 -DSYN_USE_SPI_ASYNC=1 -DSYN_FW_USE_HMAC=1 -DSYN_USE_MULTICORE=1 -DUNITY_INCLUDE_DOUBLE -DSYN_USE_METRICS=1 -DSYN_USE_ROUTER=1 -DSYN_USE_LIN=1 -DSYN_USE_LINTP=1 -DSYN_USE_GBT27930=1 -DSYN_USE_CANNM=1 -DSYN_USE_IR=1 -DSYN_USE_SMBUS=1 -DSYN_USE_PMBUS=1 -DSYN_USE_MBUS=1 -DSYN_USE_DLT645=1 -DSYN_USE_AT_PARSER=1 -DSYN_USE_BACNET=1 -DSYN_USE_DEVICENET=1 -DSYN_USE_YMODEM=1 -DSYN_USE_AUDIO=1 -DSYN_USE_ADPCM=1 -DSYN_USE_SBC=1


# All SyntropicOS source files
SYN_SRCS := \
	src/syntropic/audio/syn_adpcm.c \
	src/syntropic/audio/syn_sbc.c \
	src/syntropic/audio/syn_audio.c \
	src/syntropic/audio/syn_audio_mixer.c \
	src/syntropic/audio/syn_wav.c \
	src/syntropic/proto/syn_at_parser.c \
	src/syntropic/proto/syn_dlt645.c \
	src/syntropic/drivers/syn_gpio.c src/syntropic/drivers/syn_uart.c \
	src/syntropic/drivers/syn_adc.c src/syntropic/drivers/syn_exti.c \
	src/syntropic/drivers/syn_can.c src/syntropic/drivers/syn_soft_i2c.c \
	src/syntropic/drivers/syn_soft_spi.c src/syntropic/drivers/syn_sd.c \
	src/syntropic/drivers/syn_rtc.c src/syntropic/drivers/syn_soft_onewire.c \
	src/syntropic/drivers/syn_dac.c src/syntropic/drivers/syn_dma.c \
	src/syntropic/drivers/syn_pwm.c src/syntropic/drivers/syn_hrpwm.c \
	src/syntropic/drivers/syn_comp.c src/syntropic/drivers/syn_i2c.c \
	src/syntropic/drivers/syn_spi.c src/syntropic/drivers/syn_i2c_queue.c \
	src/syntropic/drivers/syn_spi_queue.c \
	src/syntropic/util/syn_ringbuf.c src/syntropic/util/syn_fsm.c \
	src/syntropic/util/syn_crc.c src/syntropic/util/syn_fmt.c \
	src/syntropic/util/syn_ramp.c src/syntropic/util/syn_scurve.c \
	src/syntropic/util/syn_cbor_write.c src/syntropic/util/syn_cbor_read.c \
	src/syntropic/util/syn_pubsub.c src/syntropic/util/syn_netbuf.c \
	src/syntropic/util/syn_spsc_queue.c src/syntropic/util/syn_slab.c \
	src/syntropic/sched/syn_sched.c src/syntropic/sched/syn_timer.c \
	src/syntropic/sched/syn_watchdog.c src/syntropic/sched/syn_sequencer.c \
	src/syntropic/sched/syn_workqueue.c src/syntropic/sched/syn_timer_wheel.c \
	src/syntropic/sched/syn_event_flags.c \
	src/syntropic/log/syn_log.c src/syntropic/log/syn_datalog.c src/syntropic/cli/syn_cli.c \
	src/syntropic/input/syn_button.c src/syntropic/input/syn_encoder.c \
	src/syntropic/output/syn_led.c src/syntropic/output/syn_soft_pwm.c \
	src/syntropic/dsp/syn_filter.c src/syntropic/dsp/syn_filter_design.c \
	src/syntropic/dsp/syn_signal.c src/syntropic/dsp/syn_biquad.c \
	src/syntropic/control/syn_pid.c src/syntropic/control/syn_autotune.c \
	src/syntropic/control/syn_control_stats.c \
	src/syntropic/motor/syn_stepper.c src/syntropic/motor/syn_servo.c \
	src/syntropic/motor/syn_dc_motor.c src/syntropic/motor/syn_motor_ctrl.c \
	src/syntropic/motor/syn_actuator.c \
	src/syntropic/proto/syn_cobs.c src/syntropic/proto/syn_modbus.c \
	src/syntropic/proto/syn_modbus_master.c \
	src/syntropic/proto/syn_canopen.c src/syntropic/proto/syn_cia402.c \
	src/syntropic/proto/syn_lss.c src/syntropic/proto/syn_cia401.c \
	src/syntropic/proto/syn_cia303.c \
	src/syntropic/proto/syn_dmx512.c \
	src/syntropic/proto/syn_ccp.c \
	src/syntropic/proto/syn_xcp.c \
	src/syntropic/proto/syn_uds.c \
	src/syntropic/proto/syn_kwp2000.c \
	src/syntropic/proto/syn_uds_util.c \
	src/syntropic/proto/syn_doip.c \
	src/syntropic/proto/syn_devicenet.c \
	src/syntropic/proto/syn_isotp.c \
	src/syntropic/proto/syn_lintp.c \
	src/syntropic/proto/syn_gbt27930.c \
	src/syntropic/proto/syn_cannm.c \
	src/syntropic/proto/syn_dali.c \
	src/syntropic/proto/syn_bacnet.c \
	src/syntropic/proto/syn_ocpp.c \
	src/syntropic/proto/syn_lin.c \
	src/syntropic/proto/syn_ir.c \
	src/syntropic/proto/syn_smbus.c \
	src/syntropic/proto/syn_pmbus.c \
	src/syntropic/proto/syn_mbus.c \
	src/syntropic/proto/syn_cjt188.c \
	src/syntropic/proto/syn_canopen_mgr.c src/syntropic/proto/syn_j1939.c \
	src/syntropic/proto/syn_n2k.c src/syntropic/proto/syn_ethercat.c \
	src/syntropic/proto/syn_ymodem.c \
	src/syntropic/sensor/syn_sensor.c src/syntropic/sensor/syn_sensor_fusion.c \
	src/syntropic/storage/syn_param.c \
	src/syntropic/storage/syn_settings.c \
	src/syntropic/debug/syn_trace.c src/syntropic/debug/syn_profiler.c \
	src/syntropic/debug/syn_task_profile.c \
	src/syntropic/dsp/syn_dds.c \
	src/syntropic/system/syn_boot.c src/syntropic/system/syn_errlog.c \
	src/syntropic/system/syn_power.c src/syntropic/system/syn_hwwdt.c \
	src/syntropic/system/syn_fwupdate.c src/syntropic/system/syn_fwboot.c \
	src/syntropic/display/syn_canvas.c src/syntropic/ui/syn_menu.c \
	src/syntropic/ui/syn_imgui.c \
	src/syntropic/net/syn_router.c src/syntropic/net/syn_heartbeat.c \
	src/syntropic/net/syn_http.c src/syntropic/net/syn_httpd.c \
	src/syntropic/net/syn_transport_tcp.c \
	src/syntropic/net/syn_websocket.c \
	src/syntropic/net/syn_tcp.c \
	src/syntropic/net/syn_udp.c \
	src/syntropic/net/syn_dns.c \
	src/syntropic/net/syn_mqtt.c \
	src/syntropic/util/syn_json_write.c src/syntropic/util/syn_json_read.c \
	src/syntropic/sched/syn_ao.c \
	src/syntropic/storage/syn_vfs.c \
	src/syntropic/storage/syn_lfs.c \
	src/syntropic/net/syn_coap.c \
	src/syntropic/dsp/syn_fft.c \
	src/syntropic/system/syn_fault.c \
	src/syntropic/util/syn_sha256.c \
	src/syntropic/util/syn_aes128.c \
	src/syntropic/system/syn_coredump.c \
	src/syntropic/crypto/syn_blake2s.c \
	src/syntropic/crypto/syn_chacha20poly1305.c \
	src/syntropic/crypto/syn_x25519.c \
	src/syntropic/net/syn_sntp.c \
	src/syntropic/util/syn_stream.c \
	src/syntropic/util/syn_backoff.c \
	src/syntropic/util/syn_random.c \
	src/syntropic/util/syn_metrics.c \
	src/syntropic/util/syn_qmath.c \
	src/syntropic/util/syn_matrix.c \
	src/syntropic/util/syn_quaternion.c \
	src/syntropic/util/syn_vector.c \
	src/syntropic/util/syn_transform.c \
	src/syntropic/dsp/syn_kalman.c src/syntropic/motor/syn_foc.c \
	src/syntropic/motor/syn_foc_encoder.c \
	src/syntropic/motor/syn_foc_observer.c \
	src/syntropic/proto/syn_modbus_tcp.c src/syntropic/proto/syn_nmea.c \
	src/syntropic/motor/syn_interpolator.c \
	src/syntropic/util/syn_geo.c \
	src/syntropic/drivers/syn_hpclock.c \
	src/syntropic/drivers/syn_timesync.c \
	src/syntropic/output/syn_buzzer.c \
	src/syntropic/input/syn_keypad.c \
	src/syntropic/input/syn_touch.c \
	src/syntropic/input/syn_dipswitch.c \
	src/syntropic/display/syn_charlcd.c \
	src/syntropic/display/syn_oled.c \
	src/syntropic/display/syn_seg7.c \
	src/syntropic/drivers/syn_shiftreg.c \
	src/syntropic/drivers/syn_ioexp.c \
	src/syntropic/input/syn_joystick.c \
	src/syntropic/sensor/syn_powermon.c \
	src/syntropic/sensor/syn_climate.c \
	src/syntropic/output/syn_smartled.c \
	src/syntropic/sensor/syn_distance.c \
	src/syntropic/sensor/syn_scale.c \
	src/syntropic/sensor/syn_lux.c \
	src/syntropic/drivers/syn_rfid.c \
	src/syntropic/sensor/syn_biometric.c \
	src/syntropic/motor/syn_bldc_6step.c \
	src/syntropic/proto/syn_sbus.c \
	src/syntropic/output/syn_dshot.c \
	src/syntropic/input/syn_ppm.c \
	src/syntropic/proto/syn_crsf.c \
	src/syntropic/proto/syn_ibus.c \
	src/syntropic/control/syn_rc_curve.c \
	src/syntropic/control/syn_rc_failsafe.c \
	src/syntropic/output/syn_dshot_telemetry.c \
	src/syntropic/control/syn_flight_pid.c \
	src/syntropic/proto/syn_msp.c \
	src/syntropic/proto/syn_mavlink.c \
	src/syntropic/log/syn_blackbox.c \
	src/syntropic/drivers/syn_usb_cdc.c \
	src/syntropic/drivers/syn_usb.c \
	src/syntropic/drivers/syn_usb_hid.c \
	src/syntropic/drivers/syn_usb_hid_keyboard.c \
	src/syntropic/drivers/syn_usb_hid_mouse.c \
	src/syntropic/drivers/syn_transport_usb_cdc.c \
	src/syntropic/drivers/syn_usb_host.c \
	src/syntropic/drivers/syn_usb_host_cdc.c \
	src/syntropic/drivers/syn_transport_usb_host_cdc.c \
	src/syntropic/net/syn_eth.c \
	src/syntropic/net/syn_dhcp.c \
	src/syntropic/net/syn_icmp.c \
	src/syntropic/net/syn_transport_udp.c \
	src/syntropic/net/syn_autoip.c \
	src/syntropic/net/syn_netcfg.c \
	src/syntropic/net/syn_igmp.c \
	src/syntropic/util/syn_nn.c \
	src/syntropic/util/syn_dsp.c \
	src/syntropic/crypto/syn_hkdf.c \
	src/syntropic/crypto/syn_asn1.c \
	src/syntropic/crypto/syn_ed25519.c \
	src/syntropic/crypto/syn_x509.c \
	src/syntropic/net/syn_tls.c \
	src/syntropic/vm/syn_wasm.c

# Unity framework
UNITY_SRCS := tests/unit/unity/unity.c

# Mock port layer
MOCK_SRCS := tests/unit/mocks/mock_port.c

# Build output directory
BUILD_DIR := build/tests

# All per-module test files
TEST_SRCS := $(wildcard tests/unit/test_*.c)

ALL_SRCS := $(SYN_SRCS) $(UNITY_SRCS) $(MOCK_SRCS) $(TEST_SRCS)
OBJS     := $(patsubst %.c,$(BUILD_DIR)/%.o,$(ALL_SRCS))

-include $(OBJS:.o=.d)

.PHONY: all test test-cov clean

all: test

WASM_CC     := clang
WASM_CFLAGS := --target=wasm32-unknown-unknown -O2 -nostdlib \
               -mbulk-memory -msign-ext -mmultivalue -mnontrapping-fptoint \
               -Wl,--no-entry -Wl,--export-all -Wl,--allow-undefined -Wl,-z,stack-size=1024
WASM_SRCS   := $(wildcard tests/wasm/*.c)
WASM_HDRS   := $(patsubst tests/wasm/%.c,$(BUILD_DIR)/wasm/%.wasm.h,$(WASM_SRCS))

$(BUILD_DIR)/wasm/%.wasm: tests/wasm/%.c
	@mkdir -p $(BUILD_DIR)/wasm
	$(WASM_CC) $(WASM_CFLAGS) $< -o $@

$(BUILD_DIR)/wasm/%.wasm.h: $(BUILD_DIR)/wasm/%.wasm
	(cd $(BUILD_DIR)/wasm && xxd -i $(notdir $<)) > $@

wasm-fixtures: $(WASM_HDRS)

$(OBJS): | wasm-fixtures

$(BUILD_DIR)/%.o: %.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

$(BUILD_DIR)/test_unity: $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $@ -lm $(LDFLAGS)

.PHONY: test-cov FORCE

test-cov: CFLAGS += --coverage
test-cov: LDFLAGS += --coverage
test-cov: FORCE
	rm -f $(BUILD_DIR)/test_unity
	$(MAKE) -f tests/Makefile.unity $(BUILD_DIR)/test_unity CFLAGS="$(CFLAGS) --coverage" LDFLAGS="$(LDFLAGS) --coverage"
	./$(BUILD_DIR)/test_unity

test: $(BUILD_DIR)/test_unity
	./$(BUILD_DIR)/test_unity

ARM_CC      := arm-none-eabi-gcc
ARM_CFLAGS  := -MMD -MP -mcpu=cortex-m4 -mthumb -mabi=aapcs -mfloat-abi=soft -mno-unaligned-access -std=c99 -pedantic -Wall -Wextra \
               -O2 -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables \
               -ffunction-sections -fdata-sections -I. -Isrc -Itests/unit -Itests/unit/mocks -I$(BUILD_DIR) \
               -DSYN_LOG_COLOR=0 -DSYN_LOG_USE_PRINTF=0 -DSYN_USE_COREDUMP=1 -DSYN_COREDUMP_FLASH_ADDR=0 -DSYN_USE_TICKLESS=1 \
               -DSYN_USE_DMA=1 -DSYN_USE_I2C_ASYNC=1 -DSYN_USE_SPI_ASYNC=1 -DSYN_FW_USE_HMAC=1 -DSYN_USE_MULTICORE=1 \
               -DUNITY_OUTPUT_CHAR=semihosting_putc -DUNITY_FLUSH=qemu_flush_dummy -DUNITY_EXCLUDE_FLOAT_PRINT -DUNITY_EXCLUDE_DOUBLE -DSYN_USE_METRICS=1 -DSYN_USE_ROUTER=1 -DSYN_USE_LIN=1 -DSYN_USE_LINTP=1 -DSYN_USE_GBT27930=1 -DSYN_USE_CANNM=1 -DSYN_USE_IR=1 \
               -DSYN_USE_SMBUS=1 -DSYN_USE_PMBUS=1 -DSYN_USE_MBUS=1 -DSYN_USE_DLT645=1 -DSYN_USE_AT_PARSER=1 \
               -DSYN_USE_BACNET=1 -DSYN_USE_DEVICENET=1 -DSYN_USE_YMODEM=1 \
               -Wno-unused-parameter -Wno-unused-variable -Wno-unused-but-set-variable -Wno-format -Wno-stringop-truncation -Wno-type-limits

ARM_OBJS    := $(patsubst %.c,$(BUILD_DIR)/arm/%.o,$(ALL_SRCS))

-include $(ARM_OBJS:.o=.d)

$(BUILD_DIR)/arm/%.o: %.c tests/Makefile.unity | wasm-fixtures
	@mkdir -p $(dir $@)
	$(ARM_CC) $(ARM_CFLAGS) -c $< -o $@

$(BUILD_DIR)/test_cortexm4.elf: tests/emulation/startup_cortexm4.c $(ARM_OBJS) tests/emulation/qemu_arm.ld tests/Makefile.unity
	$(ARM_CC) $(ARM_CFLAGS) -T tests/emulation/qemu_arm.ld tests/emulation/startup_cortexm4.c $(ARM_OBJS) -Wl,--gc-sections -Wl,--start-group -lc -lm -lrdimon -Wl,--end-group -o $@

.PHONY: qemu-build

qemu-build: wasm-fixtures $(BUILD_DIR)/test_cortexm4.elf




clean:
	rm -f test_unity test_unity_cov coverage.info coverage_src.info
	rm -rf coverage_html $(BUILD_DIR)
	find . \( -name "*.gcda" -o -name "*.gcno" -o -name "*.su" \) -delete
