FROM docker.io/library/gcc:13

WORKDIR /workspace

COPY . /workspace

RUN gcc -O2 -std=c99 -D_DEFAULT_SOURCE -Iinclude -Isrc -Isrc/syntropic/proto -Isrc/syntropic/util -Isrc/syntropic/port_stubs -Wall -Wextra -Werror \
    src/syntropic/proto/syn_doip.c \
    src/syntropic/proto/syn_uds.c \
    src/syntropic/crypto/syn_aes.c \
    src/syntropic/port_stubs/syn_port_stubs.c \
    tests/integration/services/doip/doip_server_runner.c \
    -o /usr/local/bin/doip_server_runner

EXPOSE 13400/tcp 13400/udp 10888/tcp 10888/udp

CMD ["/usr/local/bin/doip_server_runner"]
